services:
  - type: web
    name: rhynia-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn services.rhynia_saas.backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        value: postgresql://postgres.argbmsljgfmevthutqpu:Maniwh%402007zzzz@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
      - key: SUPABASE_URL
        value: https://argbmsljgfmevthutqpu.supabase.co
      - key: SUPABASE_PROJECT_ID
        value: argbmsljgfmevthutqpu
      - key: OPENROUTER_API_KEY
        value: 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
      - key: OPENROUTER_BACKUP_KEY
        value: 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
      - key: GEMINI_API_KEY
        value: AQ.Ab8RN6IcQJ9ylCArnSlnK5m_WkrwWRjm1WgxweH_L1Hh2a9GfQ
      - key: GEMINI_BACKUP_KEY
        value: AQ.Ab8RN6L-5Z8FqYhyXbH727BNJ4EXgvq-HkMF4fcgZltLuCBBBQ
      - key: JWT_SECRET
        value: rhynia_super_secure_jwt_secret_key_2026_horizon_luminescent
      - key: GOOGLE_CLIENT_ID
        value: 1001346913265-qbdhpbb69gen2mvcjtu56jepn1sld8os.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: FAST2SMS_API_KEY
        value: ZREic30HSxnBehfXKM29VdCrTFjaDNogkz4J1ylAQqpU5mIwG8NvBRVM3ueYnICoQ0UEchZkHtT6b48z
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_USER
        value: mk6611236@gmail.com
      - key: SMTP_PASSWORD
        value: nldgbrmonepawpqw
      - key: SMTP_FROM_NAME
        value: Rhynia Intelligence
