"""
Rhynia Intelligence SaaS — Document Export Service (PDF & Presentation)
"""

import io
from typing import Dict, List


class ExportService:
    """Handles structured document export for conversation summaries."""

    def generate_text_document(self, title: str, messages: List[Dict[str, str]]) -> bytes:
        """Generate formatted document bytes from conversation history."""
        output = io.StringIO()
        output.write(f"# {title.upper()}\n")
        output.write(f"Generated by Rhynia Intelligence\n")
        output.write("=" * 60 + "\n\n")

        for msg in messages:
            role_label = "USER" if msg.get("role") == "user" else "RHYNIA"
            output.write(f"[{role_label}]:\n")
            output.write(f"{msg.get('content', '').strip()}\n\n")
            output.write("-" * 40 + "\n\n")

        return output.getvalue().encode("utf-8")

    def generate_presentation_outline(self, topic: str, content: str) -> Dict[str, any]:
        """Generate structured slides data structure from content."""
        paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
        slides = []

        # Slide 1: Title
        slides.append({
            "slide_number": 1,
            "type": "title",
            "title": topic,
            "subtitle": "Prepared by Rhynia Intelligence",
        })

        # Content slides
        for idx, para in enumerate(paragraphs[:5], start=2):
            lines = [l.strip() for l in para.split("\n") if l.strip()]
            slide_title = lines[0][:50] if lines else f"Section {idx - 1}"
            bullet_points = lines[1:] if len(lines) > 1 else [para[:180]]

            slides.append({
                "slide_number": idx,
                "type": "content",
                "title": slide_title,
                "bullets": bullet_points[:4],
            })

        return {
            "presentation_title": topic,
            "total_slides": len(slides),
            "slides": slides,
        }


export_service = ExportService()
